## NumPy Practice
---

In [2]:
import numpy as np

In [ ]:
# Arrays
array = np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# Operations on the array
array = array * 2
print(array)
array = array // 2
print(array)

[2 4 6 8]
[1 2 3 4]


In [19]:
# Dimensions of the array
array = np.array([[1,2],[3,4],[5,6]])
print(array.ndim)
print(array.shape)

2
(3, 2)


In [23]:
# Accessing elements
print(array[0][0])
print(array[1, 1])

1
4


In [35]:
# Slicing array array[start:end:step]
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print(array[1:4])
print(array[0:4:2])
print(array[:, :1])


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]


In [39]:
# Scalar arithmetics
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print(array + 1)
print(array - 1)
print(array ** 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]


In [44]:
# Vectorized math functions
array = np.array([1.3, 2.5, 3.8])

print(np.sqrt(array))
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))

[1.14017543 1.58113883 1.94935887]
[1. 2. 4.]
[2. 3. 4.]
[1. 2. 3.]


In [48]:
# Element-wise arithmetics
a = np.array([1,2,3])
b = np.array([2,3,4])

print(a + b)
print(a - b)
print(a * b)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]


In [51]:
# Comparison operators

scores = np.array([91, 53, 88, 100, 64])

print(scores == 100)
print(scores >= 60)

[False False False  True False]
[ True False  True  True  True]


In [55]:
# Broadcasting
a = np.array([[1,2,3,4]])
b = np.array([[1], [2], [3], [4]])

print(a.shape)
print(b.shape)
print(a * b)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [62]:
# Agregate functions
array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.min(array))
print(np.max(array))

print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
1
10
[15 40]


In [69]:
# Filtering
ages = np.array([
    [21, 17, 19, 20, 16, 30, 18, 65],
    [39, 22, 15, 99, 18, 19, 20, 21]
])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <= 65)]

print(teenagers)
print(adults)

seniors = np.where(ages >= 65, ages, 0)
print(seniors)

[17 16 15]
[21 19 20 30 18 65 39 22 18 19 20 21]
[[ 0  0  0  0  0  0  0 65]
 [ 0  0  0 99  0  0  0  0]]


In [48]:
# Random Numbers
rng = np.random.default_rng()

print(rng.integers(1, 7, (3, 4)))
print(np.random.uniform(-1, 1, (2, 2)))

[[1 5 2 4]
 [3 3 5 5]
 [2 3 1 5]]
[[-0.52560875 -0.85934447]
 [-0.28541829  0.1682863 ]]
